### ISSUE TITLE
cannot connect to Mqtt

### ISSUE THREAD

**Issue by goldendatahub** [yukulehe/gazpar2mqtt#11]
I cannot connect to Mqtt, I don't know why for now.  
I have tried to run the script directly on my Debian, I have the same issue.
So it seems not related to the add-on.

_Originally posted by @Minims in https://github.com/yukulehe/gazpar2mqtt/issues/5#issuecomment-972969423_

**Comment by Minims** [comment]
So I have not the answer for now. but the error for the mqtt lib is 
`[Errno -2] Name or service not known`

I have print params and it seems OK. I usually used `paho` lib for MQTT so I have some difficulties to found the issue here.

I have tried to setup the mqtt host with IP or HOSTNAME, but same issue.
Any idea ?

**Comment by goldendatahub** [comment]
The error indicates clearly a problem of network. But hard to answer because I don't know your config.
Your Mqtt broker is an add-on of HASS (so I guess on the same host) or a self hosted container ?
Do you have the same issue with the enedisgateway2mqtt Hass add-on which, I suppose, target the same mqtt broker ?

**Comment by Minims** [comment]
It's the official mqtt broker available in HA Supervisor : 

```
Mosquitto broker
Current version: 6.0.1 (Changelog)
```

```
logins:
  - username: *********
    password: *********
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

I use it with for all my others add-on without issue.
For example the enedisgateway use it without issue and the add-on is made by @alexbelgium too
Yes Broker, gazpar2mqtt, enedisGW, etc are working on the same PI Host.
