### ISSUE TITLE
Probleme installation docker

### ISSUE THREAD

**Issue by EmilienAU** [yukulehe/gazpar2mqtt#59]
Bonjour,

Tout d'abord merci pour ton projet 👍 
Lors de l'installation sur docker avec la commande suivante j'ai l'erreur ci dessous

`docker run --name gazpar2mqtt -e GRDF_USERNAME=XXXX -e GRDF_PASSWORD=XXXXX -e MQTT_USERNAME=XXX e- MQTT_PASSWORD=XXXX -e MQTT_HOST=192.168.1.54 -e MQTT_PORT=1883 -e MQTT_CLIENTID=gazou -e MQTT_QOS=1 -e MQTT_TOPIC=gazpar -e MQTT_RETAIN=False --tty yukulehe/gazpar2mqtt:latest`

![image](https://user-images.githubusercontent.com/75580074/148686601-5439fb7a-ec08-483e-b2a0-188ad39e1674.png)

Merci d'avance pour ton aide
Emilien

**Comment by goldendatahub** [comment]
Salut Emlien,

Merci pour ton retour. Je regarde dans la matinée. Peut-être que si tu réinitialises la db ça permettrait de te débloquer (variable d'environnement DB_INIT=True, ou argument --db_init=True)

**Comment by EmilienAU** [comment]
Salut,

J'ai toujours le même problème. ci dessous le détail de conf du container

J'ai essayé avec l'addon de HA j'ai le même message d'erreur. https://github.com/alexbelgium/hassio-addons/tree/master/gazpar2mqtt

```
version: '3'
services:
  gazpar2mqtt:
    container_name: gazpar2mqtt
    image: yukulehe/gazpar2mqtt:latest
    environment:
      - GRDF_USERNAME=XXXX
      - GRDF_PASSWORD=XXXXX
      - MQTT_HOST=192.168.1.54
      - MQTT_PORT=1883
      - MQTT_CLIENTID=gazou
      - MQTT_USERNAME=XXXX
      - MQTT_PASSWORD=XXXX
      - MQTT_QOS=1
      - MQTT_TOPIC=gazpar
      - MQTT_RETAIN=False
      - HASS_DISCOVERY=True
      - DB_INIT=True
    labels:
      - com.centurylinklabs.watchtower.enable=true
```




![image](https://user-images.githubusercontent.com/75580074/148765696-1d303e90-684a-460c-94c1-672892776f31.png)
